import "./globals.css";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";
import NavBar from "~/components/NavBar";
import { Grid, Typography } from "~/components/mui";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <Typography variant="h5">
          <center>
            Welcome to the Microsoft Authentication Library For NextJS App
            Router Quickstart
          </center>
        </Typography>
        <br />
        <br />
        <Grid container justifyContent="center">
          {children}
        </Grid>
      </body>
    </html>
  );
}
