export declare class Constants {
    static readonly errorDescription: string;
    static readonly error: string;
    static readonly scope: string;
    static readonly acquireTokenUser: string;
    static readonly clientInfo: string;
    static readonly clientId: string;
    static readonly authority: string;
    static readonly idToken: string;
    static readonly accessToken: string;
    static readonly expiresIn: string;
    static readonly sessionState: string;
    static readonly msalClientInfo: string;
    static readonly msalError: string;
    static readonly msalErrorDescription: string;
    static readonly msalSessionState: string;
    static readonly tokenKeys: string;
    static readonly accessTokenKey: string;
    static readonly expirationKey: string;
    static readonly stateLogin: string;
    static readonly stateAcquireToken: string;
    static readonly stateRenew: string;
    static readonly nonceIdToken: string;
    static readonly userName: string;
    static readonly idTokenKey: string;
    static readonly loginRequest: string;
    static readonly loginError: string;
    static readonly renewStatus: string;
    static readonly msal: string;
    static readonly no_user: string;
    static readonly login_hint: string;
    static readonly domain_hint: string;
    static readonly organizations: string;
    static readonly consumers: string;
    static readonly consumersUtid: string;
    static readonly sid: string;
    static readonly upn: string;
    static readonly adalIdToken: string;
    static readonly prompt_select_account: string;
    static readonly prompt_none: string;
    static readonly prompt: string;
    static readonly response_mode_fragment: string;
    static readonly resourceDelimeter: string;
    static readonly tokenRenewStatusCancelled: string;
    static readonly tokenRenewStatusCompleted: string;
    static readonly tokenRenewStatusInProgress: string;
    private static _popUpWidth;
    static popUpWidth: number;
    private static _popUpHeight;
    static popUpHeight: number;
    static readonly login: string;
    static readonly renewToken: string;
    static readonly unknown: string;
    static readonly urlHash: string;
    static readonly angularLoginRequest: string;
    static readonly userIdentifier: string;
    static readonly common: string;
}
export declare class ErrorCodes {
    static readonly loginProgressError: string;
    static readonly acquireTokenProgressError: string;
    static readonly inputScopesError: string;
    static readonly endpointResolutionError: string;
    static readonly popUpWindowError: string;
    static readonly userLoginError: string;
    static readonly userCancelledError: string;
    static readonly multipleMatchingTokensDetected: string;
    static readonly invalidState: string;
    static readonly invalidIdToken: string;
    static readonly invalid_cache_location: string;
    static readonly non_array_scopes: string;
    static readonly empty_idtoken: string;
    static readonly idtoken_parsing_error: string;
    static readonly authorityUriInvalidPath: string;
    static readonly authorityUriInsecure: string;
    static readonly invalidAuthorityType: string;
    static readonly unsupportedAuthorityValidation: string;
    static readonly b2cAuthorityUriInvalidPath: string;
    static readonly localSessionStorageNotSupported: string;
}
export declare class ErrorDescription {
    static readonly loginProgressError: string;
    static readonly acquireTokenProgressError: string;
    static readonly inputScopesError: string;
    static readonly endpointResolutionError: string;
    static readonly popUpWindowError: string;
    static readonly userLoginError: string;
    static readonly userCancelledError: string;
    static readonly multipleAuthoritiesFoundInCachePassAuthority: string;
    static readonly cacheContainsMultipleTokens: string;
    static readonly emptyArrayScopes: string;
    static readonly clientIDShouldBeSingleScope: string;
    static readonly userLoginIsRequired: string;
    static readonly invalidIdTokenInTheResponse: string;
    static readonly clientInfoNotReceivedInTheResponseFromAAD: string;
    static readonly errorOccurredDuringUnifiedCacheATS: string;
    static readonly errorOccurredInTheTokenReceivedCallbackFunction: string;
    static readonly couldNotResolveEndpoint: string;
    static readonly navigateUrlIsEmpty: string;
    static readonly localSessionStorageNotSupported: string;
    static readonly authorityUriInvalidPath: string;
    static readonly authorityUriInsecure: string;
    static readonly invalidAuthorityType: string;
    static readonly b2cAuthorityUriInvalidPath: string;
    static readonly non_array_scopes: string;
    static readonly empty_idtoken: string;
    static readonly idtoken_parsing_error: string;
}
