name: Bug Report
description: Broken or unintended behavior with one of our libraries.
labels: [bug-unconfirmed, question]
body:
    - type: markdown
      attributes:
          value: |
              ## Before Submitting your Issue
              Our GitHub issues are meant exclusively for bug reports and feature requests. Usage questions may be closed without comment. If you have a question, please check to see if your question is answered in the FAQ for the library you are using:
              - [@azure/msal-browser](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md)
              - [@azure/msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md)
              - [@azure/msal-angular](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/FAQ.md)
              - [@azure/msal-react](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/FAQ.md)

              In the case your question is not answered in the FAQ, please verify your question has not been covered on [Stack Overflow](https://stackoverflow.com/questions/tagged/msal.js).
              If you can't find a similar question on Stack Overflow, please create a new Stack Overflow thread using the tag `msal.js`.

              If you have questions about timelines, please see our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/roadmap.md). Issues pertaining to timelines without an explicit feature request may be closed without comment.

              > [!IMPORTANT]
              > If you are a Microsoft employee please post your question in our [Teams Channel](https://aka.ms/msaljs/teams) instead.

    - type: markdown
      attributes:
          value: |
              ## Issue Details

    - type: dropdown
      attributes:
          label: Core Library
          options:
              - "MSAL.js (@azure/msal-browser)"
              - "MSAL Node (@azure/msal-node)"
      validations:
          required: true

    - type: input
      attributes:
          label: Core Library Version
          description: "Please enter the latest version this issue can be reproduced in."
          placeholder: "3.1.0"
      validations:
          required: true

    - type: dropdown
      attributes:
          label: Wrapper Library
          options:
              - "MSAL Angular (@azure/msal-angular)"
              - "MSAL React (@azure/msal-react)"
              - "MSAL Node Extensions (@azure/msal-node-extensions)"
              - "Not Applicable"
      validations:
          required: true

    - type: input
      attributes:
          label: Wrapper Library Version
          description: "Please enter the latest version this issue can be reproduced in. If you are not using a wrapper library please enter 'None'"
          placeholder: "2.0.0"
      validations:
          required: true

    - type: dropdown
      attributes:
          label: Public or Confidential Client?
          description: Are you using PublicClientApplication or ConfidentialClientApplication? (Issues regarding msal-browser, msal-react and msal-angular are always "Public")
          multiple: true
          options:
              - "Public"
              - "Confidential"
      validations:
          required: true

    - type: textarea
      attributes:
          label: Description
          description: "Please briefly describe your issue."
      validations:
          required: true

    - type: textarea
      attributes:
          label: Error Message
          description: "Please provide any error message you are receiving and a stack trace."

    - type: textarea
      attributes:
          label: MSAL Logs
          description: "Please provide [verbose or trace level log messages](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md) from msal. Bug reports without verbose or trace MSAL logs will be closed without comment. Please look at our [Logging Guide](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md) for instructions on how to collect MSAL logs."

    - type: checkboxes
      attributes:
          label: Network Trace (Preferrably Fiddler)
          description: "Please send a [Fiddler trace](https://learn.microsoft.com/en-us/azure/azure-web-pubsub/howto-troubleshoot-network-trace) (strongly preferred) or .har file containing the relevant network requests and responses to msaljshelp@microsoft.com. Your are reponsible for properly sanitizing any network trace you send. **DO NOT post a network trace**, sanitized or not to this or any GitHub issue. GitHub issues for which we don't receive a corresponding network trace e-mail in a reasonable timeframe may be closed without comment."
          options:
              - label: Sent
              - label: Pending
    - type: textarea
      attributes:
          label: MSAL Configuration
          description: "Please provide your MSAL configuration. Bug reports without MSAL configuration will be closed without comment."
          render: javascript
          placeholder: |
              {
                auth: {
                  clientId: "clientId",
                  authority: "https://login.microsoftonline.com/common/"
                },
                cache: {
                  cacheLocation: "sessionStorage"
                  storeAuthStateInCookie: false
                }
              }
      validations:
          required: true

    - type: textarea
      attributes:
          label: Relevant Code Snippets
          description: "Please provide relevant code snippets that can be used to reproduce this issue."
          render: javascript
      validations:
          required: true

    - type: textarea
      attributes:
          label: Reproduction Steps
          description: "Please provide steps to reproduce or a link to a sample which demonstrates this behavior. If there is no way to consistently reproduce this issue, it may be closed without comment."
          placeholder: |
              1.
              2.
              3.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Expected Behavior
          description: "Please describe what you expect the behavior to be."
      validations:
          required: true

    - type: dropdown
      attributes:
          label: Identity Provider
          options:
              - Entra ID (formerly Azure AD) / MSA
              - Azure B2C Basic Policy
              - Azure B2C Custom Policy
              - ADFS
              - Other
      validations:
          required: true

    - type: dropdown
      attributes:
          label: Browsers Affected (Select all that apply)
          multiple: true
          options:
              - Chrome
              - Firefox
              - Edge
              - Safari
              - None (Server)
              - Other
      validations:
          required: true

    - type: input
      attributes:
          label: Regression
          description: "If this behavior worked before, please enter the last working version(s)."
          placeholder: "@azure/msal-browser 2.0.0"

    - type: markdown
      attributes:
          value: "## Security Reporting"
    - type: markdown
      attributes:
          value: |
              If you find a security issue with our libraries or services [please report it to the Microsoft Security Response Center (MSRC)](https://aka.ms/report-security-issue) with as much detail as possible. Your submission may be eligible for a bounty through the [Microsoft Bounty](http://aka.ms/bugbounty) program. Please do not post security issues to GitHub Issues or any other public site. We will contact you shortly upon receiving the information. We encourage you to get notifications of when security incidents occur by visiting [this page](https://www.microsoft.com/msrc/technical-security-notifications) and subscribing to Security Advisory Alerts.
