name: Documentation
description: Issues with documentation for one of our libraries.
labels: [documentation, question]
body:

- type: markdown
  attributes:
    value: |
      ## Before Submitting your Issue
      If there's a problem with the documentation or samples in this repo, please consider opening a PR with the necessary changes instead.
      
      You'll find our contributing doc [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/contributing.md)

      > [!IMPORTANT]
      > If you are a Microsoft employee please post your question in our [Teams Channel](https://aka.ms/msaljs/teams) instead.
      
- type: markdown
  attributes:
    value: |
      ## Issue Details

- type: dropdown
  attributes:
    label: Core Library
    multiple: true
    options: 
      - "MSAL.js (@azure/msal-browser)"
      - "MSAL Node (@azure/msal-node)"

- type: dropdown
  attributes:
    label: Wrapper Library
    multiple: true
    options:
      - "MSAL Angular (@azure/msal-angular)"
      - "MSAL React (@azure/msal-react)"
      - "MSAL Node Extensions (@azure/msal-node-extensions)"
      - "Not Applicable"
  validations:
    required: true

- type: dropdown
  attributes:
    label: Public or Confidential Client?
    description: Are you using PublicClientApplication or ConfidentialClientApplication? (Issues regarding msal-browser, msal-react and msal-angular are always "Public")
    multiple: true
    options: 
      - "Public"
      - "Confidential"
  validations:
    required: true

- type: input
  attributes:
    label: Documentation Location
    description: Please provide a link to the documentation this issue is about
    placeholder: "docs.microsoft.com"
  validations: 
    required: true

- type: textarea
  attributes:
    label: Description
    description: "Please briefly describe your issue."
  validations: 
    required: true
