name: Feature request
description: Suggest a feature for one of our libraries.
labels: [feature-unconfirmed, question]
body:
- type: markdown
  attributes:
    value: |
      ## Before Submitting your Issue
      > [!IMPORTANT]
      > If you are a Microsoft employee please submit your feature request in our [Teams Channel](https://aka.ms/msaljs/teams) instead.
      
- type: dropdown
  attributes:
    label: Core Library
    multiple: true
    options: 
      - "MSAL.js (@azure/msal-browser)"
      - "MSAL Node (@azure/msal-node)"
  validations:
    required: true

- type: dropdown
  attributes:
    label: Wrapper Library
    multiple: true
    options:
      - "MSAL Angular (@azure/msal-angular)"
      - "MSAL React (@azure/msal-react)"
      - "MSAL Node Extensions (@azure/msal-node-extensions)"
      - "Not Applicable"
  validations:
    required: true

- type: dropdown
  attributes:
    label: Public or Confidential Client?
    description: Are you using PublicClientApplication or ConfidentialClientApplication? (Issues regarding msal-browser, msal-react and msal-angular are always "Public")
    multiple: true
    options: 
      - "Public"
      - "Confidential"
  validations:
    required: true

- type: textarea
  attributes:
    label: Description
    description: "Please briefly describe the feature you are requesting."
  validations: 
    required: true
