name: Feature request
description: Suggest a feature for one of our libraries.
labels: [feature]
body:
- type: dropdown
  attributes:
    label: Core Library
    multiple: true
    options: 
      - "MSAL.js v2 (@azure/msal-browser)"
      - "MSAL.js v1 (@azure/msal or msal)"
      - "MSAL Node (@azure/msal-node)"
      - "Passport Azure AD (passport-azure-ad)"
      - "ADAL Node (adal-node)"
      - "ADAL.js (adal.js)"
  validations:
    required: true

- type: dropdown
  attributes:
    label: Wrapper Library
    multiple: true
    options:
      - "MSAL Angular (@azure/msal-angular)"
      - "MSAL React (@azure/msal-react)"
      - "MSAL Node Extensions (@azure/msal-node-extensions)"
      - "ADAL Angular (adal-angular)"
      - "Not Applicable"
  validations:
    required: true

- type: textarea
  attributes:
    label: Description
    description: "Please briefly describe the feature you are requesting."
  validations: 
    required: true

- type: dropdown
  attributes:
    label: Source
    description: "Are you an internal or external customer?"
    options: 
      - Internal (Microsoft)
      - External (Customer)
  validations: 
     required: true
