# This workflow will do a clean install of node dependencies at the root and check that a beachball change file has been committed.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Beachball Check
on:
    pull_request:
        branches:
            - dev

concurrency:
    group: beachball-${{github.ref}}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    beachball-check:
        permissions:
            contents: read # for actions/checkout to fetch code
            pull-requests: read # for dorny/paths-filter to read pull requests
        if: github.actor != 'dependabot[bot]' && !contains(github.head_ref, 'post-release') && !contains(github.head_ref, 'release-staging')
        runs-on: ubuntu-latest
        env:
            BEACHBALL: 1
        steps:
            - uses: dorny/paths-filter@0e4a8c6effa4802afeda77dc8d303f8176d7dfad # v3.0.4
              id: filter
              with:
                  # Will return true if any file is not markdown and any file is in /lib
                  filters: |
                      lib:
                        - 'lib/**/**.!(md)'
                        - 'extensions/msal-node-extensions/**/**.!(md)'

            - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
              if: ${{ steps.filter.outputs.lib == 'true' }}
              with:
                  fetch-depth: 0

            - name: Use Node.js
              if: ${{ steps.filter.outputs.lib == 'true' }}
              uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0

            - name: Install beachball
              if: ${{ steps.filter.outputs.lib == 'true' }}
              run: npm ci --workspaces=false

            - name: Run Beachball Check command
              if: ${{ steps.filter.outputs.lib == 'true' }}
              run: npm run beachball:check
